package domain

import (
	"time"

)

// Phase 31: Model Fine-Tuning, Distillation & LoRA Adapter Asset Engine
// ==========================================

// FineTuningJobType defines the nature of the training job
type FineTuningJobType string

const (
	FineTuningJobTypeDistillation FineTuningJobType = "distillation" // Generating synthetic data from teacher & training student
	FineTuningJobTypeSFT          FineTuningJobType = "sft"          // Standard supervised fine-tuning
	FineTuningJobTypeDPO          FineTuningJobType = "dpo"          // Direct preference optimization
	FineTuningJobTypeLoRATrain    FineTuningJobType = "lora_train"    // Parameter-efficient adapter fine-tuning
)

// FineTuningJobStatus tracks training pipeline progression
type FineTuningJobStatus string

const (
	FineTuningJobStatusQueued         FineTuningJobStatus = "queued"
	FineTuningJobStatusGeneratingData FineTuningJobStatus = "generating_data"
	FineTuningJobStatusTraining       FineTuningJobStatus = "training"
	FineTuningJobStatusEvaluating     FineTuningJobStatus = "evaluating"
	FineTuningJobStatusCompleted      FineTuningJobStatus = "completed"
	FineTuningJobStatusFailed         FineTuningJobStatus = "failed"
	FineTuningJobStatusCancelled      FineTuningJobStatus = "cancelled"
)

// BreakEvenStatus tracks financial recovery status of a trained adapter
type BreakEvenStatus string

const (
	BreakEvenStatusRecovering BreakEvenStatus = "recovering" // Accumulated savings < TotalCapEx
	BreakEvenStatusAchieved   BreakEvenStatus = "achieved"   // Accumulated savings >= TotalCapEx (Pure Alpha)
)

// GPUCatalogItem hardware spec and hourly market rental price
type GPUCatalogItem struct {
	Model         string  `json:"model"`           // e.g. "NVIDIA-H100-SXM", "NVIDIA-A100-80G", "NVIDIA-L40S", "RTX-4090"
	VRAMGB        int     `json:"vram_gb"`         // e.g. 80, 48, 24
	HourlyRateUSD float64 `json:"hourly_rate_usd"` // e.g. 3.50, 2.20, 1.20, 0.60
	Category      string  `json:"category"`        // "Flagship Hopper", "Enterprise Ampere", "Cost-Effective Inference/Fine-tuning"
	Description   string  `json:"description"`
}

// FineTuningJob full record of a fine-tuning or distillation pipeline
type FineTuningJob struct {
	ID               string              `json:"id"`
	TenantID         string              `json:"tenant_id"`
	Name             string              `json:"name"`
	JobType          FineTuningJobType   `json:"job_type"`
	Status           FineTuningJobStatus `json:"status"`
	BaseModel        string              `json:"base_model"`         // Student model e.g. "Qwen/Qwen2.5-7B-Instruct"
	TeacherModel     string              `json:"teacher_model"`      // e.g. "DeepSeek-R1" or "gpt-4o"
	TargetAdapterID  string              `json:"target_adapter_id"`  // e.g. "lora-quant-sentiment-v2"
	GPUModel         string              `json:"gpu_model"`          // e.g. "NVIDIA-H100-SXM"
	GPUCount         int                 `json:"gpu_count"`          // e.g. 8
	DurationHours    float64             `json:"duration_hours"`     // e.g. 4.5
	ComputeCostUSD   float64             `json:"compute_cost_usd"`   // GPU hours * rate
	SyntheticTokens  int                 `json:"synthetic_tokens"`   // Tokens generated by teacher
	SyntheticSamples int                 `json:"synthetic_samples"`  // Number of synthetic QA pairs
	SyntheticCostUSD float64             `json:"synthetic_cost_usd"` // Teacher generation invoice
	EvalMetric       string              `json:"eval_metric"`        // e.g. "MMLU", "F1", "Accuracy"
	EvalScore        float64             `json:"eval_score"`         // e.g. 84.6%
	EvalCostUSD      float64             `json:"eval_cost_usd"`      // Benchmark evaluation cost
	TotalCapExUSD    float64             `json:"total_capex_usd"`    // Compute + Synthetic + Eval
	ErrorMessage     string              `json:"error_message,omitempty"`
	CreatedAt        time.Time           `json:"created_at"`
	CompletedAt      *time.Time          `json:"completed_at,omitempty"`
}

// LoRAAdapterAsset financialized adapter tracking continuous inference savings
type LoRAAdapterAsset struct {
	ID                   string          `json:"id"`                     // e.g. "lora-quant-sentiment-v2"
	TenantID             string          `json:"tenant_id"`
	Name                 string          `json:"name"`
	BaseModel            string          `json:"base_model"`             // e.g. "Qwen/Qwen2.5-7B"
	BenchmarkModel       string          `json:"benchmark_model"`        // e.g. "gpt-4o"
	JobID                string          `json:"job_id"`
	TotalCapExUSD        float64         `json:"total_capex_usd"`        // Total training cost to recover
	AvgCostBenchmarkUSD  float64         `json:"avg_cost_benchmark_usd"` // e.g. $0.015 per call on gpt-4o
	AvgCostStudentUSD    float64         `json:"avg_cost_student_usd"`   // e.g. $0.0015 per call on 7B + LoRA
	UnitSavedUSD         float64         `json:"unit_saved_usd"`         // Benchmark - Student ($0.0135)
	InferenceCount       int64           `json:"inference_count"`        // Total production calls
	TotalSavingsUSD      float64         `json:"total_savings_usd"`      // InferenceCount * UnitSaved
	NetAlphaUSD          float64         `json:"net_alpha_usd"`          // TotalSavings - TotalCapEx (if > 0)
	ROIPercent           float64         `json:"roi_percent"`            // TotalSavings / TotalCapEx * 100
	BreakEvenInvocations int64           `json:"break_even_invocations"` // TotalCapEx / UnitSaved
	Status               BreakEvenStatus `json:"status"`                 // recovering vs achieved
	CreatedAt            time.Time       `json:"created_at"`
	UpdatedAt            time.Time       `json:"updated_at"`
}

// FineTuningStatsSummary macro metrics for the dashboard
type FineTuningStatsSummary struct {
	TotalCapExUSD            float64 `json:"total_capex_usd"`
	ActiveAdapters           int     `json:"active_adapters"`
	TotalInferenceSavingsUSD float64 `json:"total_inference_savings_usd"`
	NetAlphaSavingsUSD       float64 `json:"net_alpha_savings_usd"`
	PortfolioROI             float64 `json:"portfolio_roi"`
	AchievedAdapters         int     `json:"achieved_adapters"`
	TotalJobs                int     `json:"total_jobs"`
	CompletedJobs            int     `json:"completed_jobs"`
}

// FineTuningJobCreateRequest payload to launch a training/distillation job
type FineTuningJobCreateRequest struct {
	TenantID         string            `json:"tenant_id,omitempty"`
	Name             string            `json:"name"`
	JobType          FineTuningJobType `json:"job_type"`
	BaseModel        string            `json:"base_model"`
	TeacherModel     string            `json:"teacher_model,omitempty"`
	TargetAdapterID  string            `json:"target_adapter_id"`
	GPUModel         string            `json:"gpu_model"`
	GPUCount         int               `json:"gpu_count"`
	DurationHours    float64           `json:"duration_hours"`
	SyntheticSamples int               `json:"synthetic_samples,omitempty"`
	SyntheticTokens  int               `json:"synthetic_tokens,omitempty"`
	BenchmarkModel   string            `json:"benchmark_model,omitempty"`
}

// LoRAAdapterCreateRequest payload to register an adapter
type LoRAAdapterCreateRequest struct {
	TenantID            string  `json:"tenant_id,omitempty"`
	ID                  string  `json:"id"`
	Name                string  `json:"name"`
	BaseModel           string  `json:"base_model"`
	BenchmarkModel      string  `json:"benchmark_model"`
	JobID               string  `json:"job_id,omitempty"`
	TotalCapExUSD       float64 `json:"total_capex_usd"`
	AvgCostBenchmarkUSD float64 `json:"avg_cost_benchmark_usd"`
	AvgCostStudentUSD   float64 `json:"avg_cost_student_usd"`
}

// FineTuningSimulateTurn month-by-month trajectory in the flywheel sandbox
type FineTuningSimulateTurn struct {
	Month                       int             `json:"month"`
	MonthlyInvocations          int64           `json:"monthly_invocations"`
	CumulativeInvocations       int64           `json:"cumulative_invocations"`
	CumulativeFlagshipSpendUSD  float64         `json:"cumulative_flagship_spend_usd"`
	CumulativeDistilledSpendUSD float64         `json:"cumulative_distilled_spend_usd"`
	CumulativeNetSavingsUSD     float64         `json:"cumulative_net_savings_usd"`
	NetROIPercent               float64         `json:"net_roi_percent"`
	Status                      BreakEvenStatus `json:"status"`
}

// FineTuningSimulateRequest payload for interactive flywheel simulation
type FineTuningSimulateRequest struct {
	TeacherModel       string  `json:"teacher_model"`        // e.g. "gpt-4o"
	StudentModel       string  `json:"student_model"`        // e.g. "Qwen-2.5-7B"
	SyntheticSamples   int     `json:"synthetic_samples"`    // e.g. 100000
	GPUModel           string  `json:"gpu_model"`            // e.g. "NVIDIA-H100-SXM"
	GPUCount           int     `json:"gpu_count"`            // e.g. 8
	TrainingHours      float64 `json:"training_hours"`        // e.g. 6.0
	MonthlyInvocations int64   `json:"monthly_invocations"`  // e.g. 500000
	BenchmarkModel     string  `json:"benchmark_model"`      // e.g. "gpt-4o"
}

// FineTuningSimulateResponse response for flywheel simulation
type FineTuningSimulateResponse struct {
	TotalCapExUSD          float64                  `json:"total_capex_usd"`
	SyntheticCostUSD       float64                  `json:"synthetic_cost_usd"`
	ComputeCostUSD         float64                  `json:"compute_cost_usd"`
	UnitSavedUSD           float64                  `json:"unit_saved_usd"`
	BreakEvenInvocations   int64                    `json:"break_even_invocations"`
	BreakEvenMonths        float64                  `json:"break_even_months"`
	YearOneSavingsUSD      float64                  `json:"year_one_savings_usd"`
	YearOneNetAlphaUSD     float64                  `json:"year_one_net_alpha_usd"`
	Timeline               []FineTuningSimulateTurn `json:"timeline"`
	FinOpsRecommendations []string                 `json:"finops_recommendations"`
}

// ==========================================
// Phase 33: Heterogeneous Multi-Cloud AI Compute, KV-Cache VRAM Virtualization
// & Disaggregated Prefill/Decode Cost Engine
// =========================================================================

// HeteroNodeType defines the execution runtime environment
type HeteroNodeType string

const (
	HeteroNodeBareMetal  HeteroNodeType = "bare_metal_gpu"
	HeteroNodeK8sPod     HeteroNodeType = "k8s_vllm_pod"
	HeteroNodeServerless HeteroNodeType = "cloud_serverless"
	HeteroNodeEdge       HeteroNodeType = "edge_ollama"
)

// HeteroPhase defines inference workload stage
type HeteroPhase string

const (
	HeteroPhasePrefill HeteroPhase = "prefill"
	HeteroPhaseDecode  HeteroPhase = "decode"
	HeteroPhaseHybrid  HeteroPhase = "hybrid"
)

// HeteroBurstStatus defines the scheduling dispatch destination
type HeteroBurstStatus string

const (
	HeteroBurstLocal        HeteroBurstStatus = "local_scheduled"
	HeteroBurstCloud        HeteroBurstStatus = "cloud_bursted"
	HeteroBurstQueued       HeteroBurstStatus = "queued_waiting"
	HeteroBurstRejectedOOM  HeteroBurstStatus = "rejected_oom"
)

// HeteroGPUNode represents an on-premise or cloud-attached physical/virtual GPU instance
type HeteroGPUNode struct {
	ID                   string         `json:"id"`
	Hostname             string         `json:"hostname"`
	GPUModel             string         `json:"gpu_model"` // e.g. "NVIDIA-H100-SXM", "NVIDIA-A100-80G-PCIe", "NVIDIA-L40S"
	GPUCount             int            `json:"gpu_count"`
	HourlyRateUSD        float64        `json:"hourly_rate_usd"`
	TotalVRAMGB          float64        `json:"total_vram_gb"`
	StaticWeightVRAMGB   float64        `json:"static_weight_vram_gb"`
	DynamicKVCacheVRAMGB float64        `json:"dynamic_kv_cache_vram_gb"`
	FreeVRAMGB           float64        `json:"free_vram_gb"`
	VRAMUtilPercent      float64        `json:"vram_util_percent"`
	NodeType             HeteroNodeType `json:"node_type"`
	ActiveModel          string         `json:"active_model"`
	MaxBatchConcurrency  int            `json:"max_batch_concurrency"`
	CurrentConcurrency   int            `json:"current_concurrency"`
	MFUScore             float64        `json:"mfu_score"` // Model FLOPs Utilization 0~100
	MBUScore             float64        `json:"mbu_score"` // Memory Bandwidth Utilization 0~100
	Status               string         `json:"status"`    // "online", "high_watermark", "draining", "offline"
	UpdatedAt            time.Time      `json:"updated_at"`
}

// HeteroResourcePool aggregates heterogeneous nodes with high-watermark burst policies
type HeteroResourcePool struct {
	ID                                string   `json:"id"`
	Name                              string   `json:"name"`
	TargetModel                       string   `json:"target_model"`
	NodeIDs                           []string `json:"node_ids"`
	HighWatermarkPercent              float64  `json:"high_watermark_percent"` // default e.g. 85.0%
	EnablePrefillDecodeDisaggregation bool     `json:"enable_prefill_decode_disaggregation"`
	PrefillNodeIDs                    []string `json:"prefill_node_ids,omitempty"`
	DecodeNodeIDs                     []string `json:"decode_node_ids,omitempty"`
	CloudBurstProvider                string   `json:"cloud_burst_provider"` // "runpod", "modal", "aws_bedrock"
	CloudBurstCostPer1MTokens         float64  `json:"cloud_burst_cost_per_1m_tokens"`
	Enabled                           bool     `json:"enabled"`
}

// HeteroUsageTrace details a single heterogeneous inference execution and physical metering
type HeteroUsageTrace struct {
	ID                     string            `json:"id"`
	TraceID                string            `json:"trace_id"`
	TenantID               string            `json:"tenant_id"`
	Model                  string            `json:"model"`
	Phase                  HeteroPhase       `json:"phase"`
	ScheduledNodeID        string            `json:"scheduled_node_id"`
	NodeType               HeteroNodeType    `json:"node_type"`
	BurstStatus            HeteroBurstStatus `json:"burst_status"`
	PromptTokens           int               `json:"prompt_tokens"`
	CompletionTokens       int               `json:"completion_tokens"`
	DurationMs             int64             `json:"duration_ms"`
	VRAMAllocationGB       float64           `json:"vram_allocation_gb"`
	VRAMResidenceCostUSD   float64           `json:"vram_residence_cost_usd"`
	PrefillComputeCostUSD  float64           `json:"prefill_compute_cost_usd"`
	DecodeBandwidthCostUSD float64           `json:"decode_bandwidth_cost_usd"`
	TotalCostUSD           float64           `json:"total_cost_usd"`
	EquivalentCloudCostUSD float64           `json:"equivalent_cloud_cost_usd"`
	HybridSavingsUSD       float64           `json:"hybrid_savings_usd"`
	MFUScore               float64           `json:"mfu_score"`
	MBUScore               float64           `json:"mbu_score"`
	Timestamp              time.Time         `json:"timestamp"`
}

// HeteroStatsSummary provides global metrics on heterogeneous clusters and hybrid economics
type HeteroStatsSummary struct {
	TotalInvocations           int64   `json:"total_invocations"`
	LocalScheduledCount        int64   `json:"local_scheduled_count"`
	CloudBurstedCount          int64   `json:"cloud_bursted_count"`
	BurstRatioPercent          float64 `json:"burst_ratio_percent"`
	AvgVRAMUtilPercent         float64 `json:"avg_vram_util_percent"`
	AvgMFUScore                float64 `json:"avg_mfu_score"`
	AvgMBUScore                float64 `json:"avg_mbu_score"`
	TotalCostUSD               float64 `json:"total_cost_usd"`
	TotalEquivalentCloudCostUSD float64 `json:"total_equivalent_cloud_cost_usd"`
	TotalHybridSavingsUSD      float64 `json:"total_hybrid_savings_usd"`
	ActiveNodesCount           int     `json:"active_nodes_count"`
	TotalPhysicalVRAMGB        float64 `json:"total_physical_vram_gb"`
}

// HeteroDispatchRequest simulates or evaluates request placement
type HeteroDispatchRequest struct {
	TenantID                  string      `json:"tenant_id,omitempty"`
	Model                     string      `json:"model"`
	Prompt                    string      `json:"prompt,omitempty"`
	PromptTokens              int         `json:"prompt_tokens"`
	EstimatedCompletionTokens int         `json:"estimated_completion_tokens"`
	RequestedPhase            HeteroPhase `json:"requested_phase,omitempty"`
}

// HeteroDispatchResponse returns the scheduling decision and estimated physical costs
type HeteroDispatchResponse struct {
	ScheduledNodeID      string            `json:"scheduled_node_id"`
	NodeType             HeteroNodeType    `json:"node_type"`
	BurstStatus          HeteroBurstStatus `json:"burst_status"`
	CurrentVRAMUtil      float64           `json:"current_vram_util"`
	EstimatedCostUSD     float64           `json:"estimated_cost_usd"`
	EquivalentCloudCostUSD float64         `json:"equivalent_cloud_cost_usd"`
	PredictedSavingsUSD  float64           `json:"predicted_savings_usd"`
	MFUScore             float64           `json:"mfu_score"`
	MBUScore             float64           `json:"mbu_score"`
	RoutingReason        string            `json:"routing_reason"`
}

// HeteroSimulateTurn records a step in multi-tenant concurrency simulation
type HeteroSimulateTurn struct {
	StepIndex          int               `json:"step_index"`
	Concurrency        int               `json:"concurrency"`
	PromptLength       int               `json:"prompt_length"`
	ScheduledNodeID    string            `json:"scheduled_node_id"`
	BurstStatus        HeteroBurstStatus `json:"burst_status"`
	VRAMUtilPercent    float64           `json:"vram_util_percent"`
	CostUSD            float64           `json:"cost_usd"`
	EquivalentCloudUSD float64           `json:"equivalent_cloud_usd"`
	SavingsUSD         float64           `json:"savings_usd"`
	Detail             string            `json:"detail"`
}

// HeteroSimulateRequest configures a What-If concurrency spike simulation
type HeteroSimulateRequest struct {
	Concurrency            int  `json:"concurrency"`
	AvgPromptTokens        int  `json:"avg_prompt_tokens"`
	AvgCompletionTokens    int  `json:"avg_completion_tokens"`
	EnablePDDisaggregation bool `json:"enable_pd_disaggregation"`
	SimulatedRounds        int  `json:"simulated_rounds"`
}

// HeteroSimulateResponse outputs simulation results and cluster architecture advice
type HeteroSimulateResponse struct {
	TotalRequests               int                  `json:"total_requests"`
	LocalHandled                int                  `json:"local_handled"`
	CloudBursted                int                  `json:"cloud_bursted"`
	CloudBurstPercent           float64              `json:"cloud_burst_percent"`
	MaxVRAMPeakUtil             float64              `json:"max_vram_peak_util"`
	TotalHybridCostUSD          float64              `json:"total_hybrid_cost_usd"`
	PureCloudCostUSD            float64              `json:"pure_cloud_cost_usd"`
	NetSavingsUSD               float64              `json:"net_savings_usd"`
	SavingsPercent              float64              `json:"savings_percent"`
	Timeline                    []HeteroSimulateTurn `json:"timeline"`
	ArchitectureRecommendations []string             `json:"architecture_recommendations"`
}

// =========================================================================
// Phase 34: Synthetic Data Flywheel, Quality-to-Cost Valuation
// & RLHF/DPO Preference Alignment Cost Engine
// =========================================================================

type FlywheelDataCategory string

const (
	FlywheelCategoryMathReasoning FlywheelDataCategory = "reasoning_math"
	FlywheelCategoryCodeRepair    FlywheelDataCategory = "code_repair"
	FlywheelCategoryMultiTurnChat FlywheelDataCategory = "multi_turn_chat"
	FlywheelCategorySafetyAlign   FlywheelDataCategory = "safety_alignment"
	FlywheelCategoryMath          FlywheelDataCategory = "reasoning_math"
	FlywheelCategoryCoding        FlywheelDataCategory = "code_repair"
	FlywheelCategoryAgentic       FlywheelDataCategory = "agentic_trace"
	FlywheelCategoryChat          FlywheelDataCategory = "multi_turn_chat"
)

type FlywheelAlignmentAlgorithm string

const (
	FlywheelAlgoDPO FlywheelAlignmentAlgorithm = "dpo" // Direct Preference Optimization
	FlywheelAlgoPPO FlywheelAlignmentAlgorithm = "ppo" // Proximal Policy Optimization
	FlywheelAlgoKTO FlywheelAlignmentAlgorithm = "kto" // Kahneman-Tversky Optimization
)

type FlywheelHarvestStatus string

const (
	FlywheelStatusCandidatePooled FlywheelHarvestStatus = "candidate_pooled"
	FlywheelStatusScoredAccepted  FlywheelHarvestStatus = "scored_accepted"
	FlywheelStatusScoredRejected  FlywheelHarvestStatus = "scored_rejected"
	FlywheelStatusDiscarded       FlywheelHarvestStatus = "discarded"
	FlywheelStatusAccepted        FlywheelHarvestStatus = "scored_accepted"
)

// FlywheelPreferencePair represents a verified preference pair
type FlywheelPreferencePair struct {
	ID                 string    `json:"id"`
	DatasetID          string    `json:"dataset_id"`
	Prompt             string    `json:"prompt"`
	ChosenCompletion   string    `json:"chosen_completion"`
	RejectedCompletion string    `json:"rejected_completion"`
	ChosenScore        float64   `json:"chosen_score"`
	RejectedScore      float64   `json:"rejected_score"`
	MarginDelta        float64   `json:"margin_delta"` // ChosenScore - RejectedScore
	TeacherModel       string    `json:"teacher_model"`
	CandidateCount     int       `json:"candidate_count"` // e.g. 4 or 8
	CreatedAt          time.Time `json:"created_at"`
}

// FlywheelDatasetBatch aggregates synthetic preference generation & rejection sampling yield
type FlywheelDatasetBatch struct {
	ID                       string               `json:"id"`
	Name                     string               `json:"name"`
	Category                 FlywheelDataCategory `json:"category"`
	TeacherModel             string               `json:"teacher_model"`
	TotalGeneratedCandidates int                  `json:"total_generated_candidates"`
	AcceptedPairsCount       int                  `json:"accepted_pairs_count"`
	AcceptanceRatePercent    float64              `json:"acceptance_rate_percent"`
	GenerationCostUSD        float64              `json:"generation_cost_usd"`
	SunkRejectionCostUSD     float64              `json:"sunk_rejection_cost_usd"`
	TotalDatasetCostUSD      float64              `json:"total_dataset_cost_usd"`
	CostPerValidPairUSD      float64              `json:"cost_per_valid_pair_usd"`
	AvgMarginDelta           float64              `json:"avg_margin_delta"`
	Status                   string               `json:"status"` // "ready", "generating", "archived"
	CreatedAt                time.Time            `json:"created_at"`
}

// FlywheelAlignmentJob models a DPO or PPO RLHF alignment training execution
type FlywheelAlignmentJob struct {
	ID                  string                     `json:"id"`
	Name                string                     `json:"name"`
	DatasetID           string                     `json:"dataset_id"`
	TargetModel         string                     `json:"target_model"`
	ReferenceModel      string                     `json:"reference_model"`
	Algorithm           FlywheelAlignmentAlgorithm `json:"algorithm"` // "dpo" or "ppo"
	GPUModel            string                     `json:"gpu_model"` // e.g. "NVIDIA H100 SXM5"
	GPUCount            int                        `json:"gpu_count"`
	TotalGPUHours       float64                    `json:"total_gpu_hours"`
	PeakVRAMGB          float64                    `json:"peak_vram_gb"`
	GradientStepCostUSD float64                    `json:"gradient_step_cost_usd"`
	TotalJobCostUSD     float64                    `json:"total_job_cost_usd"`
	FinalLoss           float64                    `json:"final_loss"`
	RewardMarginGain    float64                    `json:"reward_margin_gain"`
	Status              string                     `json:"status"` // "completed", "running", "failed"
	CreatedAt           time.Time                  `json:"created_at"`
}

// FlywheelUsageTrace tracks an online inference query harvested or served by aligned model
type FlywheelUsageTrace struct {
	ID            string                `json:"id"`
	TraceID       string                `json:"trace_id"`
	TenantID      string                `json:"tenant_id"`
	Prompt        string                `json:"prompt"`
	Completion    string                `json:"completion"`
	Harvested     bool                  `json:"harvested"`
	HarvestStatus FlywheelHarvestStatus `json:"harvest_status"`
	DatasetID     string                `json:"dataset_id,omitempty"`
	PairValueUSD  float64               `json:"pair_value_usd"`
	ModelVersion  string                `json:"model_version"` // e.g. "dpo-aligned-v2"
	Timestamp     time.Time             `json:"timestamp"`
}

// FlywheelStatsSummary aggregates macroeconomic KPIs for the synthetic data flywheel
type FlywheelStatsSummary struct {
	TotalGeneratedCandidates  int     `json:"total_generated_candidates"`
	TotalAcceptedPairs        int     `json:"total_accepted_pairs"`
	AvgAcceptanceRatePercent  float64 `json:"avg_acceptance_rate_percent"`
	TotalGenerationCostUSD    float64 `json:"total_generation_cost_usd"`
	TotalSunkRejectionCostUSD float64 `json:"total_sunk_rejection_cost_usd"`
	TotalAlignmentCapExUSD    float64 `json:"total_alignment_capex_usd"`
	TotalOnlineInvocations    int64   `json:"total_online_invocations"`
	TotalInferenceSavingsUSD  float64 `json:"total_inference_savings_usd"`
	OverallFlywheelROIPercent float64 `json:"overall_flywheel_roi_percent"`
	ActiveJobsCount           int     `json:"active_jobs_count"`
}

// FlywheelHarvestRequest evaluates an online input/output pair for flywheel storage
type FlywheelHarvestRequest struct {
	TenantID        string `json:"tenant_id,omitempty"`
	Prompt          string `json:"prompt"`
	Completion      string `json:"completion"`
	TeacherModel    string `json:"teacher_model,omitempty"`
	TargetDatasetID string `json:"target_dataset_id,omitempty"`
}

// FlywheelHarvestResponse returns candidate quality score and decision
type FlywheelHarvestResponse struct {
	Harvested             bool                  `json:"harvested"`
	HarvestStatus         FlywheelHarvestStatus `json:"harvest_status"`
	QualityScore          float64               `json:"quality_score"`
	MarginDelta           float64               `json:"margin_delta"`
	EstimatedPairValueUSD float64               `json:"estimated_pair_value_usd"`
	DatasetID             string                `json:"dataset_id"`
	Detail                string                `json:"detail"`
}

// FlywheelSimulateTurn records a step in multi-stage flywheel ROI simulation
type FlywheelSimulateTurn struct {
	StageName             string  `json:"stage_name"` // "Data Synthesis", "Rejection Filtering", "Alignment Training", "Online Serving"
	MonthlySpendUSD       float64 `json:"monthly_spend_usd"`
	MonthlySavingsUSD     float64 `json:"monthly_savings_usd"`
	NetCumulativeAlphaUSD float64 `json:"net_cumulative_alpha_usd"`
	MetricDetail          string  `json:"metric_detail"`
}

// FlywheelSimulateRequest configures What-If data flywheel simulation
type FlywheelSimulateRequest struct {
	SeedPromptScale          int                        `json:"seed_prompt_scale"` // e.g. 10000
	CandidateMultiplier      int                        `json:"candidate_multiplier"` // e.g. 4 or 8
	Algorithm                FlywheelAlignmentAlgorithm `json:"algorithm"` // dpo or ppo
	TargetModelSize          string                     `json:"target_model_size"` // "7b", "14b", "70b"
	MonthlyOnlineInvocations int                        `json:"monthly_online_invocations"` // e.g. 500000
}

// FlywheelSimulateResponse outputs full lifecycle ROI and recommendations
type FlywheelSimulateResponse struct {
	TotalSynthesisCostUSD      float64                `json:"total_synthesis_cost_usd"`
	TotalSunkRejectionUSD      float64                `json:"total_sunk_rejection_usd"`
	TotalAlignmentCapExUSD     float64                `json:"total_alignment_capex_usd"`
	TotalInitialInvestmentUSD  float64                `json:"total_initial_investment_usd"`
	MonthlyInferenceSavingsUSD float64                `json:"monthly_inference_savings_usd"`
	BreakEvenMonths            float64                `json:"break_even_months"`
	FirstYearNetAlphaUSD       float64                `json:"first_year_net_alpha_usd"`
	FlywheelROIPercent         float64                `json:"flywheel_roi_percent"`
	Stages                     []FlywheelSimulateTurn `json:"stages"`
	ArchitectureAdvice         []string               `json:"architecture_advice"`
}






