apiVersion: v1
kind: Service
metadata:
  name: {{ include "aimeter.fullname" . }}-backend
  labels:
    {{- include "aimeter.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.backend.service.otlpGrpcPort }}
      targetPort: otlp-grpc
      protocol: TCP
      name: otlp-grpc
    - port: {{ .Values.backend.service.otlpHttpPort }}
      targetPort: otlp-http
      protocol: TCP
      name: otlp-http
  selector:
    {{- include "aimeter.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
